name = "GPJ"
uuid = "1e25b1b3-a3a0-53b8-8729-934c9d7c4cc0"
version = "0.0.1"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
PyCall = "1"
julia = "1"
