name = "GPnet"
uuid = "1e25b1b3-a3a0-53b8-8729-934c9d7c4cc0"
version = "0.0.1"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
PyCall = "1"
julia = "1"
